name: Docker Build and Push

on:
  push:
    branches: [ k3ss, main ]
    paths:
      - 'k3ss-IDE/**'
  pull_request:
    branches: [ k3ss, main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push WebUI image
        uses: docker/build-push-action@v4
        with:
          context: ./k3ss-IDE
          file: ./k3ss-IDE/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: k3ss-official/k3ss-ide-webui:latest
      
      - name: Build and push Electron image
        uses: docker/build-push-action@v4
        with:
          context: ./k3ss-IDE/electron
          push: ${{ github.event_name != 'pull_request' }}
          tags: k3ss-official/k3ss-ide-electron:latest
